from pathlib import Path

class ComputationStore:
    def __init__(self, path: Path) -> None: ...
    def contains(self, name: str) -> bool: ...
    def put_file(self, name: str, source: Path) -> str: ...
    def get_file(self, name: str, destination: Path) -> str | None: ...
    def delete(self, name: str) -> bool: ...
    def get(self, key: str) -> bytes | None: ...
    def set(self, key: str, value: bytes) -> None: ...
    def remove(self, key: str) -> bool: ...
